### ISSUE TITLE
Relative Controls on the Overworld

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#119]
## Suggested Feature 
Enable the player to press a direction to move to a new node, with that direction being relative to the current positions of the current and target nodes. 

## Requirements 
1.  All possible target nodes (i.e. those connected to the current node) are assigned a direction based on their relative position.
    1. The direction they've been assigned is shown on screen. 
2. When the player presses the assigned direction they move to the relevant node. 
3. The connections between the current node and the possible target nodes are drawn in a different colour to the rest of the node connections. 

## Additional Context
Images showing arrows being drawn to demonstrate assigned direction (based on relative position):
![image](https://user-images.githubusercontent.com/23128268/131146773-4f1b4360-5c5b-43ad-9892-667d80e78f4b.png)
![image](https://user-images.githubusercontent.com/23128268/131147399-c9410306-6974-42ce-b194-61c020438f4b.png)

Related discussion:
https://www.reddit.com/r/roguelikedev/comments/pc63tn/making_directional_input_dynamic_and_relative_to/

**Comment by snayff** [comment]
Closed in #146 . 
Whilst the functionality for the controls has been added the images have not. The approach to how the controls are handled is unclear to me and the defining of the direction each node corresponds to exists in only one place, outside of the rendering, so cannot be co-opted. As such, the button press indicators have not been added.
