### ISSUE TITLE
Warn Player When They go to Start Combat with Less than Max Units

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#135]
## Suggested Feature 
If the player can play more units but has pressed to start then ask for confirmation. 

## Requirements 
1. When the player attempts to start the combat and they could place more units (has units and can afford) they are asked for confirmation. 
    1. If the player cancels they resume placing units. 
    2. If the player confirms then combat begins.

## Additional Context
None.

**Comment by snayff** [comment]
No longer relevant
