### ISSUE TITLE
Standardise use of (x, y) and x  y 

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#142]
## Suggested Feature 
Sometimes using `self.pos = (x, y)` sometimes `self.x` and `self.y`. Standardise.

**Comment by andrewhong04** [comment]
Hi, I would love to work on this enhancement. Would you prefer using pygame's Vector system instead?

**Comment by snayff** [comment]
@novialriptide I think there used to be some challenges with the `pygame.Vector2`, but if they're sorted now (or I am mistaken!) then they would work fine. 

We have `self.pos: Tuple[int, int] = (x, y)`, `self.x: int, self.y: int` and `self.pos: List[int, int] = [x, y]` for some reason, so as long as we end up with a standard approach I dont mind!

**Comment by andrewhong04** [comment]
> self.pos: List[int, int]

I looked at the code and it looks like `size`, `offset`, etc have Lists as well. To avoid a lengthy pull request, I'll just go with `self.pos: Tuple[int, int] = (x, y)` since that looks like it's the most common one.

**Comment by snayff** [comment]
You're a star, @novialriptide . I'll take a look when back at my pc tomorrow.
