### ISSUE TITLE
Choose Destination Post Scene Completion

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#164]
## Suggested Feature 
After completing a scene the player must choose which scene to go to next.

## Requirements 
- [x]  Once a scene is complete the player is offered options  to exit from between 1-3 directions. In each direction is a new room. 
- [ ] ~~The room in each direction is indicated (e.g. if the room to the north is an Inn then the Inn icon is shown)~~
- [x] Once selected, the camera pans to the new room (which is of the specified type)
- [x] New room choices are randomly generated.
- [x] A player cannot go back to a previous room

## Additional Context
Related #163

**Comment by snayff** [comment]
Partially depends on #233

**Comment by snayff** [comment]
For the sake of simplicity, ignoring requirement to move in different directions.
