### ISSUE TITLE
Troupe Arrangement on Grid

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#165]
## Suggested Feature 
When arranging the Troupe utilise a grid. 

## Requirements 
- [x] Troupe starts in room on grid.
- [x] Troupe placement is retained between rooms.
- [x] The player can select a unit and move their position on the grid. 
- [x] If the player moves a unit to a grid cell that already has a unit then those units swap places. 
- [x] support for keyboard
- [x] support for gamepad
- [x] support for mouse

## Additional Context
Using a grid speeds up placement and enables use of a controller. 

Example:
![image](https://user-images.githubusercontent.com/23128268/148442390-a9d520ed-3c5a-45d6-8489-3f515b4efd80.png)

**Comment by snayff** [comment]
Added control types

**Comment by snayff** [comment]
Closed in #238
