### ISSUE TITLE
Convert Inn Scene to Overlay-Type Scene

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#171]
## Suggested Feature 
Rather than a menu screen, show the Inn options on screen. 

## Requirements 
- [x] Show the available Units on screen.
- [x] Player can select the available unit. 
- [ ] After selecting the available unit, the player can select a position on the Unit grid. This purchases the Unit. 
- [x] The cost of the Unit is shown by each available Unit. Affordability is shown by colour. 

## Additional Context
None..

**Comment by snayff** [comment]
Unit is given a free cell on grid.
