### ISSUE TITLE
Convert the Combat Scene to Overlay-Type Scene

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#180]
## Suggested Feature 
Rather than a discrete scene, handle the combat directly on the map.

## Requirements 
- [x] Spawn the enemy Units on to the map
- [x] Handle combat on the map
- [x] Return player units to their start position post combat

## Additional Context
Likely to use 1 of 2 approaches:
1. require changing the `WorldScene` to handle the enemy Unit's spawning and then their combat with the player's Units
2. having the `CombatScene` as an additional active scene on the stack and hiding the player's units from `WorldScene` and adding them to `CombatScene`.

**Comment by snayff** [comment]
@douglascdev be as sweeping as needed to get this in a decent place. I think the whole combat design might need a rethink.

**Comment by snayff** [comment]
Assigned to myself to pick up in tandem with #181
