### ISSUE TITLE
Bring the Combat Code Up To Snuff

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#181]
## Suggested Feature 
Improve the Combat code. 

## Requirements 
- [x] Follow the same architecture as the other scenes
     - [x] Avoid big methods
     - [x] Use methods over functions
     - [x] All data and logic should be in the `Scene`
     - [x] Rendering and input related functionality should be in the `UI`
     - [x] All attributes declared in `__init__`
- [ ] Use UI elements, in line with other screens
- [x] Add type hinting (focus on new stuff, dont worry about going back to add to everything)

## Additional Context
May be impacted by #180 
Combat code is currently messy and follows a different approach to _everything_, in contrast to the rest of the scenes.

**Comment by snayff** [comment]
Currently no UI type element to render.
