### ISSUE TITLE
Black Space Shown When Camera Moves

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#229]
## The Bug
when the camera starts it move backwards and shows a black space

## Reproduction Instructions
Detail the steps to reproduce the bug. 

1. Move to a new room

## Expected behaviour
The world is shown, never any gaps such as plain black.

## Screenshots
https://i.postimg.cc/9Xnz42fX/python-Cm72n-Pxcy-C.gif

## Platform
Describe the system and setup you were using when the bug happened. 

 - OS: Windows 10
 - Python Version: 3.9
 - NQP Version: 0.0.1

## Log Output/Stack Trace
None

**Comment by bitcraft** [comment]
fixed with #232
