### ISSUE TITLE
Lazy loading images

### ISSUE THREAD

**Issue by douglascdev** [Snayff/nqp2#318]
## Suggested Feature 
Currently, the game takes 9.24 seconds to open for me on an HD. The performance benchmarking log suggests that the main reason is the "Visual" module taking 7.62 seconds to load, mostly because of the images in the event_images folder.

After a crude implementation of [lazy image loading](https://www.pygame.org/wiki/LazyImageLoading) the startup took 2.02 seconds, with Visual taking 0.45 seconds, less than 6% of the time.

The obvious drawback is that since the loading times are split between the places they are first referred to in the code, some players could experience a hiccup in FPS when loading some images for the first time. I think the tradeoff is worth it, especially as most images would seemingly load when transitioning from one scene to another, and most images are very small anyway.

## Requirements 
- [x] Instead of loading every image into memory when the game starts, load them as they are asked for.

**Comment by snayff** [comment]
Love it, yes please!
