### ISSUE TITLE
Line wrapping

### ISSUE THREAD

**Issue by PuddingChef** [Snayff/nqp2#50]
## Suggested Feature 
Please implement line wrapping to allow narrative/story text elements to display over multiple lines.

**Comment by snayff** [comment]
Line wrapping is ostensibly in, but doesnt seem to be working. Setting a line width does stop the text being written passed that point but doesnt wrap it on to a new line. Need this to be fixed to work as intended.

**Comment by PuddingChef** [comment]
Could a different solution be to allow forced line returns through code (typically i believe it is with "\n"?)

This could simultaneously solve the paragraph feature request at the same time, potentially. Just a though?

**Comment by snayff** [comment]
@PuddingChef aye, could do. Would be nice to have the system do it for us, though!

**Comment by PuddingChef** [comment]
@Snayff agreed, actual text wrapping would be the ideal
