### ISSUE TITLE
Text Effects

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#76]
## Suggested Feature 
Additional text effects. 

## Requirements 
Text fade in. 
Multiple colours within the same block. 
Create new line in text.

## Additional Context
![C2mjprwzB5](https://user-images.githubusercontent.com/23128268/129487872-649d6c1e-c98d-4b9c-9b5b-3a5a8709fa7e.gif)

**Comment by snayff** [comment]
Replaces #55
