### ISSUE TITLE
AI Behaviours

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#77]
## Suggested Feature 
Distinct AI behaviours to differentiate unit behaviour. 

## Requirements 
Each Unit has a class. This determines their orders/behaviour and also implies the stat values they will have.

1. Light Infantry: 
    - Target: Nearest.
    - Positioning: Prioritise being in attack range.
    - Additional rules: None.
5. Heavy Infantry: 
    - Target: Nearest.
    - Positioning: Prioritise being close to Entities in Unit.
    -  Additional rules: 
        1. When changing targets, regroup, moving Entities close to one another.
10. Light Cavalry: 
    - Target: Nearest enemy of * Ranged class within X range.
    - Positioning: Prioritise being in attack range.
    - Additional rules: 
        1. Spend up to Y seconds moving to a position with an unblocked line to the target and charge; if after the duration the target is still blocked by another Unit then charge anyway, hitting the blocking unit. 
        15. After Z seconds retreat and repeat.
16. Heavy Cavalry:
    - Target: Nearest enemy of * Infantry class within X range.
    - Positioning: Prioritise being close to Entities in Unit.
    - Additional rules: 
        1. Spend up to Y seconds moving to a position with an unblocked line to the target and charge; if after the duration the target is still blocked by another Unit then charge anyway, hitting the blocking unit. 
        2. After Z seconds retreat and repeat.
        3. When changing targets, regroup, moving Entities close to one another.
23. Light Ranged: 
    - Target: Nearest, outside of minimum range.
    - Positioning: Prioritise being in attack range.
    - Additional rules: 
        1. Stay out of melee range, unless out of Ammo.
27. Heavy Ranged: 
    - Target: Nearest, outside of minimum range.
    - Positioning: Prioritise being close to Entities in Unit.
    - Additional rules:
        1.  Only move if no enemy is in range.
        2.  When changing targets, regroup, moving Entities close to one another.

**Comment by snayff** [comment]
Note from fluffy:

> 1. "Ranged" is determined by whether or not 0 ammo is given so that you can have ranged units that just reach far and don't create projectiles.
 > 2. There are a few new fields that the unit configs aren't updated with (such as projectile info). Almost all of the units are still set to use the old AI.
> 3. The Ranged AI is build into the Base AI (based on detected ammo), so LightRanged and LightInfantry use the same AI type.

**Comment by snayff** [comment]
No longer required.
