### ISSUE TITLE
Combat Animations

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#79]
## Suggested Feature 
Units should transition between appropriate animations.

## Requirements 
- [x] When moving and under no other state an entity animates as Move
- [x] When attacking the entity animates as Attack
- [x] When an entity is on screen, before combat has started, they should animate as Idle. 
- [x] When hit the entity flashes white.
- [x] When hit points become 0 or less the entity should animate as Death
- [x] After completion of the death animation cycle the last frame of the death animation should be left at that position.

**Comment by DaFluffyPotato** [comment]
The hit animation doesn't mix in very well with everything else. It disrupts the other animations and makes the combat visually confusing. I'll leave it in for now, but you can remove it easily if you search for the `comment me out to remove the hit animation` line.

**Comment by snayff** [comment]
@DaFluffyPotato  Reckon we need like a momentary stun when hit to make it work?

**Comment by DaFluffyPotato** [comment]
That would cause several issues from a design perspective. Single powerful entities would be permanently stunned when surrounded.

**Comment by snayff** [comment]
Agreed. Potentially we could use a max stunned time to prevent going into the hit animation/stun for a period after hitting that limit. Not one for now.
