### ISSUE TITLE
Unit Death and Injury

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#82]
## Suggested Feature 
When a unit dies in combat an injury is applies. 3 injuries and the unit dies and is removed from the player's troupe. 

## Requirements 
1. When a unit dies in combat they receive an injury. 
2. A unit receives -10% to all stats per injury. 
3. When a unit receives 3 injuries they are removed the player Troupe.
4. The player is informed at the first opportunity outside of combat that a unit has died. 
5. If a unit doesnt take part in combat they remove 1 injury.

**Comment by DaFluffyPotato** [comment]
I'm not going to modify unit range as a result of injury because it can result in some broken behavior with melee units.

Skipping weight/size as well.

**Comment by snayff** [comment]
Closed in #146 . 
Can't find code for unit death so doesnt look to be in. Will need adding.
