### ISSUE TITLE
Combat Placement

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#83]
## Suggested Feature 
Enemy units are only placed on 1/4 of the screen. The player can only place on 1/4 of the screen, on the opposite side. 

## Requirements 
1. For each combat, the player and enemy are each only to place units on 1/4 of the screen, on opposite sides. 
2. Placement areas are highlighted to indicate. 
3. The unit the player is currently placing is indicated. 
4. The player's placed units are indicated. 
5.  Spawn all entities when unit placed so they all appear together, rather than popping them out when combat begins.
6. Keep cursor at the same position after making a selection, i.e. placing a unit.

## Additional Context
![image](https://user-images.githubusercontent.com/23128268/129489841-c1982737-0b04-4200-9be0-51530ba8cd85.png)

**Comment by snayff** [comment]
@DaFluffyPotato added numbers 5 & 6. Let me know if that changes any estimates or is a concern and I'll move to another issue.

**Comment by snayff** [comment]
Closed in #146 .
