### ISSUE TITLE
Replace Cards with Buttons

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#85]
## Suggested Feature 
Replace the unit and skill cards with buttons. 

## Requirements 
1. Units are selected with buttons. 
2. Skills are selected with buttons. 
3. If there are more than 10 units then scrolling to the far left or right of the unit selection scrolls the units along, displaying new units. 

## Additional Context
Unit buttons:
![chrome_lt0wd1jNoh](https://user-images.githubusercontent.com/23128268/129490518-4f4a5121-7637-4375-98d2-9b45e30ee2d3.png)
Skill buttons:
![chrome_xsxLtl4m3Z](https://user-images.githubusercontent.com/23128268/129490521-bcaad47b-adbe-4970-addd-c011294fb057.png)

**Comment by snayff** [comment]
Closed in #146.
Scrolling seems to occur after 3 units, rather than 10 as specified.
