### ISSUE TITLE
Generated Combat Terrain/Tiles

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#86]
## Suggested Feature 
Randomly generate the tile and terrain placement for each combat. 

## Requirements 
1. Tileset is specified by level. 
2. Tiles are generated randomly for each combat. 
3. Terrain is generated randomly for each combat. 
4. A clear path between the left and right of the screen must be available, to ensure units can get to one another. 

## Additional Context
![chrome_lt0wd1jNoh](https://user-images.githubusercontent.com/23128268/129490799-80d8e2e9-0b5a-458c-97aa-cca1fc5a4c7f.png)

**Comment by snayff** [comment]
No longer required.
