### ISSUE TITLE
Updated Post Combat

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#87]
## Suggested Feature 
After combat, show some unit stats. 

## Requirements 
1. Show stats per unit after combat;
    1. Damage dealt
    2. Damage received
    3. Kills
2. Show if an injury has been received or removed. 
3. Show if a unit has died. 

## Additional Context
![image](https://user-images.githubusercontent.com/23128268/129491225-77a7ee73-e18c-40ac-a538-636958d762a5.png)

**Comment by snayff** [comment]
Closed in #146 .
Indication of units that died is not in. Will create a new issue.
